services:
  static-site:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - shared-network
    container_name: cv.fnyaoo.com
    
networks:
  shared-network:
    external: true