services:
  static-site:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - shared-network
    container_name: cv.fnyaoo.com
    ports:
      - "3002:3002"

networks:
  shared-network:
    external: true
