name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PROJECT_FOLDER=/root/${{ github.event.repository.name }}

            if [ ! -d "$PROJECT_FOLDER/.git" ]; then
              git clone https://github.com/${{ github.repository }} $PROJECT_FOLDER
            fi

            cd $PROJECT_FOLDER
            git reset --hard
            git pull origin master

            docker compose down --rmi all
            docker compose up -d --build
